; Ex05 - Solicitar números até o usuário enviar um input vazio, imprimir em ordem crescente (bubble sort)
START:
  ZERA R2
READ_LOOP:
  ENTRADA R0
  CAR_IMD R1,0
  SUBTRAI R0,R1
  SALTA_Z SORT
  CAR_IMD R1,48
  SUBTRAI R0,R1
  ES_INDIRETO R0,R2
  INC R2
  SALTA READ_LOOP
SORT:
  EMPILHA R2       ; guarda N
  DEC R2           ; passes = N-1
OUTER_LOOP:
  ZERA R0          ; j = 0
INNER_LOOP:
  COPIA R1,R0
  SUBTRAI R1,R2    ; j - passes
  SALTA_C COMPARE
  SALTA NEXT_PASS
COMPARE:
  LE_INDIRETO R1,R0
  EMPILHA R1
  INC R0
  LE_INDIRETO R1,R0
  DESEMPILHA R3
  SUBTRAI R3,R1
  SALTA_C NOSWAP
  DEC R0
  ES_INDIRETO R1,R0
  INC R0
  ES_INDIRETO R3,R0
  DEC R0
NOSWAP:
  INC R0
  SALTA INNER_LOOP
NEXT_PASS:
  DEC R2
  SALTA_NZ OUTER_LOOP
  DESEMPILHA R2    ; restaura N
PRINT:
  ZERA R0
  CAR_IMD R3,48
PRINT_LOOP:
  LE_INDIRETO R1,R0
  SOMA R1,R3
  SAIDA R1
  INC R0
  COPIA R1,R0
  SUBTRAI R1,R2
  SALTA_NZ PRINT_LOOP
END:
  NADA
